version: '3.9'
services:
  db:
    image: postgres:16.2-alpine3.19
    env_file:
      - .env
    restart: 'on-failure'
    ports:
      - '5432:5432'
    volumes:
      - .db_data:/var/lib/postgresql/data/
  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    
volumes:
  db_data:
